name: Crypto Coin Watcher CI

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Configure PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0

    - uses: "ramsey/composer-install@v1"

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run linting
      run: composer run-script check-style

    - name: Run static analysis
      run: composer run-script stan

    - name: Run test suite
        DB_PASSWORD: postgres
      run: composer run-script test -- --stop-on-failure
